# GitHub Pages Configuration
title: Pinpoint Accessibility Checker
description: A simple and convienent accessibility testing bookmarklet powered by axe-core for digital accessibility testing
author: Center for User Experience
email: centerforux@wisc.edu

# GitHub Pages specific settings
github:
  is_project_page: true

# Theme (optional - GitHub Pages will use default if not specified)
# theme: jekyll-theme-minimal

# Custom domain (uncomment and modify if you have a custom domain)
url: "https://pinpointchecker.com"

# Base URL for GitHub Pages (usually your repository name)
baseurl: "/Pinpoint"

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .git/
  - .DS_Store

# Include files that start with underscores
include:
  - _config.yml

# Markdown processor
markdown: kramdown

# Syntax highlighting
highlighter: rouge

# Plugins (GitHub Pages supports these by default)
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# SEO and metadata
lang: en-US
timezone: America/Chicago

# Navigation and structure
navigation:
  - title: Home
    url: /
  - title: Local Testing
    url: /local-test.html
  - title: Simple Version
    url: /bookmarklet-simple.html

# Social and institutional information
organization:
  name: University of Wisconsin System
  url: https://www.wisconsin.edu/
  accessibility_url: https://www.wisconsin.edu/accessibility/

# Tool information
tool:
  name: Pinpoint Accessibility Checker
  version: "1.0"
  powered_by: axe-core
  standards:
    - WCAG 2.0 Level A
    - WCAG 2.0 Level AA
    - WCAG 2.1 Level AA
    - Section 508